
class Constants{
  static List<String>interestTags=[
    'Gaming',
    'PUBG',
    'You tubing',
    'Avengers',
    'Justice league',

    '90\'s kid',
    'Self-care',
    'Hot yoga',
    'Writing',
    'Meditation',
    'Sushi',
    'Snooker',
    'Basketball',
    'Slam poetry',
    'Home workouts',
    'Manga',
    'Aquarium',
    'Trainers',
    'Hot springs',
    'Hockey',
    'Martial arts',
    'Waking',
    'Running',
    'Travel',
    'Multi-Language',
    'Films',
    'Gym',
    'Social media',
    'Skincare',
    'Cricket',
    'Skateboarding',
    'vegan cooking',
    'K-pop',
    'Photography',
    'Reading',
    'Singing',
    'Volleyball',
    'Sports',
    'Vinyasa',
    'Poetry',
    'Stand-up comedy',
    'Coffee',
    'LeagueOfLegends',
    'Karaoke',
    'Fortnite',
    'Free diving',
    'Foodie tour',
    'Jiu-jitsu',
    'Climate change',
    'NFTs',
    'Exhibition',
    'Pub crawls',
    'Baseball',
    'LGBTQ+ rights',
    'Ballet',
    'Feminism',
    'Bands',
    'Escape cafe',
    'Sailing',
    'Shopping',
    'Brunch',
    'Reggaeton',
    'Vintage clothing',
    'Road trips',
    'Memes',
    'Country Music',
    'Motorcycling',
    'Football',
    'Acapella',
    'Investing',
    'Art galleries',
    'Hiking',
    'Mountains',
    'Archery',
    'Backpacking',
    'Fishing',
    'Ice cream',
    'Ice skating',
    'Exhibitions',
    'Skiing',
    'Snowboarding',
    'Pilates',
    'Clubbing',
    'Broadway',
    'Cheerleading',
    'Choir',
    'Car racing',
    'Street food',
    'Festivals',
    'Catan',
    'Crossfit',
    'Cosplay',
    'Motorsports',
    'Content creation',
    'E-sports',
    'Concerts',
    'Climbing',
    'Baking',
    'Camping',
    'Blogging',
    'Collecting',
    'Bicycle racing',
    'Start-ups',
    'Boba tea',
    'TV series',
    'Songwriter',
    'Tattoos',
    'Painting',
    'Paddle boarding',
    'Padel',
    'Surfing',
    'Badminton',
    'Bowling',
    'Active lifestyle',
    'Beach bars',
    'Fashion',
    'Astrology',
    'Motorcycles',
    'Entrepreneurship',
    'Cooking',
    'Fencing',
    'Dancing',
    'Gardening',
    'Amateur cook',
    'Art',
    'DIY',
    'Politics',
    'Cycling',
    'Museum',
    'Outdoors',
    'Activism',
    'Picnicking',
    'Twitch',
    'Comedy',
    'Music',
    'Triathlon',
    'Netflix',
    'Disney',
    'DAOs',
    'Real estate',
    'Podcasts',
    'BBQ',
    'Craft Beer',
    'Stocks',
    'Swimming',
    'Iced tea',
    'Drummer',
    'Tea',
    'Boardgames',
    'Drawing',
    'Trivia',
    'Volunteering',
    'Table tennis',
    'Environmentalism',
    'Rollerskating',
    'Wine',
    'Dungeons & Dragons',
    'Vlogging',
    'Electronic music',
    'Working out',
    'Yoga',
    'Boxing',
    'Ramen',

    'Animation',
    'Accounts',
    'Graphic Arts',
    'Development',
    'Bollywood',
    'Breaking bad',
    'Squid Game'


  ];

  static const allSpeeds =<double>[0.25,0.5,1,1.5,2,3,5,10];

}
